# Generated by Django 3.0 on 2020-01-25 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='board',
            new_name='player_board',
        ),
        migrations.AddField(
            model_name='game',
            name='real_board',
            field=models.TextField(blank=True, default=''),
        ),
    ]
