# Generated by Django 3.0 on 2020-01-25 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_auto_20200125_0150'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='seed',
            field=models.IntegerField(null=True),
        ),
    ]
