# Generated by Django 3.0 on 2020-01-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_seed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='game',
            name='score',
        ),
        migrations.AlterField(
            model_name='game',
            name='status',
            field=models.IntegerField(choices=[(0, 'created'), (1, 'playing'), (2, 'won'), (3, 'lost')], default=0),
        ),
    ]
